"""empty message

Revision ID: ebf7fbe6180d
Revises: 
Create Date: 2026-04-21 16:39:36.623368

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf7fbe6180d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_course_name_instructor', ['name', 'instructor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_constraint('uq_course_name_instructor', type_='unique')

    # ### end Alembic commands ###
